### ISSUE TITLE
[WEAVER] Can we pass an HTML as a string instead of a file in request body?

### ISSUE THREAD

**Issue by fleboulch** [arachnys/athenapdf#190] opened 2019-03-25 13:46 UTC
I'm trying to pass a string (e.g.: "<html>Hello World</html>") instead of a file in the request body when using the microservice?

**CURL request with a file (working fine)**
```
curl -X POST \
  'http://localhost:8081/convert?auth=arachnys-weaver&ext=html' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F file=@/home/florent/tmp/athena.html
```

**CURL request with string content (bad request)**
```
curl -X POST \
  'http://localhost:8081/convert?auth=arachnys-weaver&ext=html' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F 'file=<html>Hello</html>'
```

My `content-type` header is maybe misconfigured

**Comment by sanohin** [comment] 2019-03-26 10:27
duplicate of #180

**Closed by sanohin** 2019-03-26 10:27 UTC
