### ISSUE TITLE
How to Post HTML data to athena?

### ISSUE THREAD

**Issue by excenter** [arachnys/athenapdf#84] opened 2017-01-13 19:52 UTC
I similar to #54 want to POST some pre-rendered HTML data to athena running as a docker instance, and receive a PDF back that I can save. 
I can't send it as a file path because the program running this is inside it's own docker container, and setting up a web server inside a container just seems dumb. 

I have some HTML that I'm trying to render 
```
<!DOCTYPE html>
<html>
<head>
....
</head>
<body>
.....
</body>
</html>
```
nothing special. 
Using Node, I've read the text of the file (a template that's already had the data mixed in) into the variable `htmlData`. 
and I'm trying to approximate the method used by #54, and POST it as such:
```
request({
            url: "http://127.0.0.1:8100/convert?auth=arachnys-weaver",
            method: "POST",
            headers: {
                "content-type": "text/html", 
            },
            body: htmlData
        }, function (error, response, body){
            console.log(error);
            // console.log(response);
            console.log(body);
        });
```
which is a bog standard post using the request library (i've also used the standard HTTP library). 

I've fiddled with changing the content type to `multipart/form-data ` which is mentioned by @MrSaints , or nothing.

all of which athena logs 
```
captured errors:
Error #01: invalid file provided

[GIN] 2017/01/13 - 19:34:51 | 400 |      118.96µs | 172.17.0.1 |   POST    /convert
```

Is there a doc I'm missing on how to POST/ what am I doing wrong?

**Comment by AlexanderSharov** [comment] 2017-01-13 20:53
Try this:
```
     const formData = {
        file: {
          value:  fs.createReadStream(filePath),
          options: {
            filename: 'input.html',
            contentType: 'text/html; charset=utf-8'
          }
        }
        
      };
      
      request.post({
        url:'http://athenapdf:8080/convert?auth=arachnys-weaver&ext=html',
        formData: formData
      }, (err, httpResponse, body)=>{
      });
```

It returned me pdf, but I have another issue here: it returns pdf with empty pages. 
More interesting, if I call GET with providing URL to my html file - everything works perfectly, but if I try to POST that html - it returns me pdf with lots of empty pages.

**Comment by excenter** [comment] 2017-01-13 21:27
is the magic in sending it as a stream, or wrapping it in a file object?

**Comment by AlexanderSharov** [comment] 2017-01-13 21:59
I don't think the problem is in the streams... You can try to use any Rest clients (e.g I prefer ARC - chrome's app) to post multipart request and you will get the same results..

**Comment by MrSaints** [comment] 2017-01-16 11:16
@AlexanderSharov solution looks appropriate to me (see https://github.com/request/request#multipartform-data-multipart-form-uploads - be sure to name the field `file` rather than `custom_file` which the example uses). 

Though, I'm quite curious as to why the results are different in the POST vs. the GET handler. If either of you don't mind, can I have a look at the HTML you are using (or something that can be used to replicate the problem)?

Thanks!

**Comment by AlexanderSharov** [comment] 2017-01-16 11:35
good morning gents,
looks like I found the problem and it was on my side, how I process the response: 
in my original code snippet I used `body` which actually was a string and saving it to the file led to error. So the correct node.js code which worked for me:
```
      let fstream = fs.createWriteStream(outputPath);
      
      request.post({
        url:'http://athenapdf:8080/convert?auth=arachnys-weaver&ext=html',
        headers: {
          authorization: 'arachnys-weaver',
        },
        formData: formData

      }).on('complete', function (){
        console.log('Request finished');

        callback(null, outputPath);

      })
      .on('error', function(err){
        callback(new Error('Unable to load pdf: ' + JSON.stringify(err)));
      }
      )
      .pipe(fstream);
```
here with using `pipe` we directly save the binary stream to filesystem without any buffer->string->buffer conversion

**Comment by MrSaints** [comment] 2017-01-16 11:50
@AlexanderSharov Glad it worked out for you 😄 And thank you for sharing your solution.
@excenter Can you let us know if it works for you?

**Comment by excenter** [comment] 2017-01-16 16:06
I will let you know as soon as I get a chance to test :)

**Comment by excenter** [comment] 2017-01-16 17:01
@AlexanderSharov I'm having trouble running that code as is, like  both `callback`s aren't defined, but I got *this* to do exactly what I wanted it to: 
```
var fs = require("fs");
var http = require('http');
var request = require('request');
var outputPath = 'ouptut.pdf';

const formData = {
    file: {
        value:  fs.createReadStream('test.html'),
        options: {
            filename: 'input.html',
            contentType: 'text/html; charset=utf-8'
        }
    }

};
let fstream = fs.createWriteStream(outputPath);
request.post({
    url:'http://127.0.0.1:8100/convert?auth=arachnys-weaver&ext=html',
    headers: {
        authorization: 'arachnys-weaver',
    },
    formData: formData

}).on('complete', function (){
    console.log('Request finished');
})
.on('error', function(err){
}
)
.pipe(fstream);

```

**Comment by MrSaints** [comment] 2017-01-18 20:12
I'll close this issue seeing as it appears to be resolved. Let me know if you have any further questions / issues.

**Closed by MrSaints** 2017-01-18 20:12 UTC
Labels: App: weaver, More Information Needed, Type: Question
