### ISSUE TITLE
table of contents

### ISSUE THREAD

**Issue by ivoputzer** [arachnys/athenapdf#79] opened 2016-11-28 10:44 UTC
is there any known way to create a table of contents based on anchor links of an html page?

**Comment by MrSaints** [comment] 2016-11-29 18:33
Possible duplicate of #16. 

Unfortunately, there's no out-of-the-box solution at the moment. It is possible however, to generate it via JavaScript.

You can also use HTML anchors to link to a specific page (see https://gist.github.com/MrSaints/cc40127b54298910a6a8 for an example on how to do so). 

Let me know if that answers your question.

**Comment by JD-Robbs** [comment] 2017-01-03 15:56
@MrSaints Does this also pertain to the ToC (navigation menu) that is rendered by PDF viewers on the left-hand side?  It would be nice to have that option to be able to quickly jump across sections (N.B. I am not referring to a ToC that is actually printed on a page).

**Comment by MrSaints** [comment] 2017-01-16 15:08
@JD-Robbs Yes, that too, isn't supported. Nevertheless, it _can be supported_ on the microservice-level. I'd prefer not to touch the CLI for that since Electron does not support it, and it's likely that we have to rely on something like GhostScript to achieve it.

**Comment by MrSaints** [comment] 2017-06-20 11:44
Let's move the discussion to #16.

**Closed by MrSaints** 2017-06-20 11:44 UTC
Labels: App: athenapdf, Resolution: Duplicate, Type: Question
