### ISSUE TITLE
Crashes at high resolution PNG

### ISSUE THREAD

**Issue by Milek7** [arachnys/athenapdf#131] opened 2017-08-22 13:18 UTC
minimal testcase:
`<img src="img.png">`
img.png is 4300x2800 white png. (doesn't have to be exact that, just big)

```
sudo docker run --rm -v $(pwd):/converted/ 139e8cc958e3 athenapdf https://milek7.pl/.stuff/athenacrashtestcase/testcase.html
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
The renderer process has crashed.
```

**Comment by MrSaints** [comment] 2017-08-22 15:38
Duplicate of #95

**Closed by MrSaints** 2017-08-22 15:38 UTC
